import Head from 'next/head'
import Image from "next/legacy/image";
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import Card from "../components/card/card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar username="ana@example.com"/>
        <Banner
            title='Clifford is the red dog'
            subtitle='He is a smart dog'
            imgUrl='/static/photo.jpg'
        />
        <Card imgUrl={'/static/photo.jpg'} size={"large"} />
        <Card  size={"medium"} />
        <Card imgUrl={'/static/photo.jpg'} size={"small"} />
    </div>
  )
}
