import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import { getVideos } from "../lib/videos";

export default function Home() {

  const disneyVideos = getVideos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar username="ana@example.com"/>
        <Banner
            title='Clifford is the red dog'
            subtitle='He is a smart dog'
            imgUrl='/static/photo.jpg'
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large"/>
          <SectionCards title="Disney" videos={disneyVideos} size="medium"/>
          <SectionCards title="Disney" videos={disneyVideos} size="small"/>
        </div>
    </div>
  )
}
