import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import { getVideos, getPopularVideos } from "../lib/videos";
import {magic} from "../lib/magic-client";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos("popular videos");
  return { props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos },
  };
}
export default function Home({ disneyVideos,
                               productivityVideos,
                               travelVideos,
                               popularVideos  }) {
  console.log({magic});

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.main}>
          <NavBar username="ana@example.com"/>
          <Banner
              title='Clifford is the red dog'
              subtitle='He is a smart dog'
              imgUrl='/static/clifford.jpg'
          />
          <div className={styles.sectionWrapper}>
            <SectionCards title="Disney" videos={disneyVideos} size="large"/>
            <SectionCards title="Travel" videos={travelVideos} size="small"/>
            <SectionCards title="Productivity" videos={productivityVideos} size="medium"/>
            <SectionCards title="Popular" videos={popularVideos} size="small"/>
          </div>
        </div>
    </div>
  )
}
